@startuml
hide circle
hide stereotype
hide members
hide methods
skinparam linetype ortho
skinparam class {
BackgroundColor<<LogicalModel>> #APPLICATION
BackgroundColor<<Profile>> #TECHNOLOGY
}
legend right
| <#APPLICATION>  Logical Model |
| <#TECHNOLOGY>  Profile |
endlegend
class "IndicatorsOah" <<LogicalModel>> [[StructureDefinition-IndicatorsOah.html]]
note top #PaleTurquoise [[ConceptMap-IndicatorsOah2FHIR.html]]
Concept Map
endnote
class "observation-indicators-oah" <<Profile>> [[StructureDefinition-observation-indicators-oah.html]]
"IndicatorsOah" <|. "observation-indicators-oah"
class "observation-with-component-oah" <<Profile>> [[StructureDefinition-observation-with-component-oah.html]]
"IndicatorsOah" <|. "observation-with-component-oah"
"observation-indicators-oah" -d[hidden]-> "observation-with-component-oah"
@enduml
