Instance: Library-Oslo-All
Title: "Library - Oslo disease prevalence dataset"
Description: "All Oslo disease prevalence observations for Nordre Aker (2024)."
InstanceOf: LibraryOah
Usage: #example
* url = "https://oneaquahealth.eu/library/OsloAll"
* identifier[0].system = "https://oneaquahealth.eu/library-id"
* identifier[0].value = "oslo-all"
* version = "2025.05"
* name = "OsloAllResults"
* title = "Oslo observations (all cohorts)"
* status = #active
* type = http://terminology.hl7.org/CodeSystem/library-type#asset-collection "Asset Collection"
* date = "2025-05-27"
* publisher = "OneAquaHealth Consortium"
* author[0].name = "Oslo Kommune"
* description = "Consolidated Oslo dataset with 81 disease prevalence observations (Nordre Aker, 2024)."
* extension[size].valueQuantity.value = 81
* extension[size].valueQuantity.unit = "observations"
* extension[numberOfRecords].valueInteger = 81

* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-long-term-disease-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-long-term-disease-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-18-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-25-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-below-30-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-bmi-above-30-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-diabate-copd-cvd-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-no-diabate-copd-cvd-Age-70-plus"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Male"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Female"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-All"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Age-18-29"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Age-30-39"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Age-40-49"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Age-50-59"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Age-60-69"
* content[+].contentType = #application/fhir+json
* content[=].url = "Observation/Obs-OS-mental-health-Age-70-plus"
